programmes: [
    {
      id: "1",
      tag: "IBM",
      title: "MBA Human Resource Management",
      subtitle: "",
      desc: "Focuses on managing an organisation’s workforce, combining core business skills with specialised HR knowledge and strategic workforce planning.",
      duration: "2 Years",
      fee: "₹3,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed a Bachelor's with 50% aggregate marks.",
    },
    {
      id: "2",
      tag: "EY",
      title: "MBA Fintech",
      subtitle: "",
      desc: "Prepares students for careers in technology-enabled finance, focusing on AI-driven financial products and services.",
      duration: "2 Years",
      fee: "₹2,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed Bachelor's with 50% aggregate marks.",
    },
    {
      id: "3",
      tag: "IIDE",
      title: "MBA Digital Marketing",
      subtitle: "",
      desc: "Teaches digital marketing strategies to navigate entrepreneurial challenges in today’s world, developed with IIDE.",
      duration: "2 Years",
      fee: "₹2,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed Bachelor's with 50% aggregate marks.",
    },
    {
      id: "4",
      tag: "IBM",
      title: "MBA Marketing ",
      subtitle: "",
      desc: "Covers topics on consumer behaviour, branding, digital strategy, and research, preparing graduates for marketing leadership across diverse industries.",
      duration: "2 Years",
      fee: "₹3,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed a Bachelor's with 50% aggregate marks.",
    },
    {
      id: "5",
      tag: "IBM",
      title: "MBA Finance",
      subtitle: "",
      desc: "Gain specialisation in finance, investments, and risk, with advanced analysis and modelling for banking and corporate leadership careers.",
      duration: "2 Years",
      fee: "₹3,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed a Bachelor's with 50% aggregate marks.",
    },
    {
      id: "6",
      tag: "IBM",
      title: "MBA International Business",
      subtitle: "",
      desc: "The course covers global markets, trade, finance, strategy, forex, and supply chains, preparing graduates for multinational careers.",
      duration: "2 Years",
      fee: "₹3,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed a Bachelor's with 50% aggregate marks.",
    },
    {
      id: "7",
      tag: "IBM",
      title: "MBA Product Marketing ",
      subtitle: "",
      desc: "Integrates core business skills with marketing strategies, product lifecycle management, plus leadership and data analysis training.",
      duration: "2 Years",
      fee: "₹3,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed a Bachelor's with 50% aggregate marks.",
    },
    {
      id: "8",
      tag: "IBM",
      title: "MBA Information Technology",
      subtitle: "",
      desc: "Programme combining core business management with specialised tech skills for business growth, innovation, and efficiency.",
      duration: "2 Years",
      fee: "₹3,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed a Bachelor's with 50% aggregate marks.",
    },
    {
      id: "9",
      tag: "IBM",
      title: "MBA Entrepreneurship",
      subtitle: "",
      desc: "Combines MBA fundamentals with innovation, fundraising, and startup growth training, & access to networks for aspiring founders.",
      duration: "2 Years",
      fee: "₹3,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed a Bachelor's with 50% aggregate marks.",
    },
    {
      id: "10",
      tag: "IBM",
      title: "MBA Operations Management",
      subtitle: "",
      desc: "A course that covers supply chain management, process optimisation, and operational excellence for efficiency, quality, and profitability.",
      duration: "2 Years",
      fee: "₹3,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed a Bachelor's with 50% aggregate marks.",
    },
    {
      id: "11",
      tag: "IBM",
      title: "MBA Business Analytics",
      subtitle: "",
      desc: "A future-ready postgraduate programme designed to develop confident & competent business leaders through an industry-aligned curriculum.",
      duration: "2 Years",
      fee: "₹3,30,000",
      ctaText: "Apply Now !",
      ctaLink: "#apply-form",
      eligibility: "Passed a Bachelor's with 50% aggregate marks.",
    },
  ],