import type { Metadata } from "next";
import "./globals.css";
import MainWebsiteLayout from "@/components/layouts/MainWebsiteLayout";

export const metadata: Metadata = {
  title: "KRMU",
  description: "Generated by KRMU",
  verification: {
    google: "-bhKCuhZrMwY93wMOanH66_uVGlrdB4ZMYSEik3Zl-M",
  },
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <MainWebsiteLayout>{children}</MainWebsiteLayout>;
}
