import type { Metadata } from "next";
import { Montserrat, Newsreader } from "next/font/google";
import "./(main-website)/globals.css";
import Script from "next/script";

const montserrat = Montserrat({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});


const newsreader = Newsreader({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "KRMU",
  description: "Generated by KRMU",
  verification: {
    google: "-bhKCuhZrMwY93wMOanH66_uVGlrdB4ZMYSEik3Zl-M",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Google Tag Manager Script */}
        <Script id="gtm-head" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-MKXDVSJ9');
          `}
        </Script>
        {/* <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-VJJK572TGN"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-VJJK572TGN');
        `}
        </Script> */}
      </head>
      <body className={`${montserrat.className} antialiased`}>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-MKXDVSJ9"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        {children}
        {/* <img
          src="https://geo.flowblinq.com/api/t/krmangalam-edu-in-uhLBq5"
          width="1"
          height="1"
          alt=""
          style={{
            position: "absolute",
            opacity: 0,
            pointerEvents: "none",
          }}
        />
        <Script
          src="https://geo.flowblinq.com/api/t/krmangalam-edu-in-uhLBq5"
          strategy="afterInteractive"
        /> */}
      </body>
    </html>
  );
}
