import type { Metadata } from "next";
import { Fraunces, Inter, Playfair_Display, Poppins } from "next/font/google";
import "./(main-website)/globals.css";
// import Script from "next/script";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-serif",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-inter",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-fraunces",
});

export const metadata: Metadata = {
  title: "KRMU",
  description: "Generated by KRMU",
  verification: {
    google: "-bhKCuhZrMwY93wMOanH66_uVGlrdB4ZMYSEik3Zl-M",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <head>
        <link
          rel="preconnect"
          href="https://truthful-cabbage-82fd27e8f6.media.strapiapp.com"
          crossOrigin="anonymous"
        />
        <link
          rel="dns-prefetch"
          href="https://truthful-cabbage-82fd27e8f6.media.strapiapp.com"
        />
        <link
          rel="preconnect"
          href="https://wp.krmangalam.edu.in"
          crossOrigin="anonymous"
        />
        <link rel="dns-prefetch" href="https://wp.krmangalam.edu.in" />
      </head>
      <body
        className={`${poppins.variable} ${playfair.variable} ${inter.variable} ${fraunces.variable} ${poppins.className} antialiased overflow-x-hidden`}
      >
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-MKXDVSJ9"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        {children}
      </body>
    </html>
  );
}
