import type { Metadata } from "next";
import { Playfair_Display, Poppins } from "next/font/google";
import "./(main-website)/globals.css";
// import Script from "next/script";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
});
export const metadata: Metadata = {
  title: "KRMU",
  description: "Generated by KRMU",
  verification: {
    google: "-bhKCuhZrMwY93wMOanH66_uVGlrdB4ZMYSEik3Zl-M",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <head>
        {/* ✅ Google Tag Manager Script */}
        {/* <Script id="gtm-head" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-MKXDVSJ9');
          `}
        </Script>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-VJJK572TGN"
          strategy="afterInteractive"
        /> */}
        {/* <Script id="google-analytics" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-VJJK572TGN');
        `}
        </Script> */}
      </head>
      <body className={`${poppins.className} ${playfair.className} ${poppins.variable} ${playfair.variable} antialiased overflow-x-hidden`}>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-MKXDVSJ9"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        {children}
      </body>
    </html>
  );
}
