export * from "./centre-for-sustainable-development-goals";
export * from "./shared-sdg";
export * from "./shared-policies";
export * as PoliciesOnNoPoverty from "./policies-on-no-poverty";
export * as PoliciesOnGoodHealthAndWellBeing from "./policies-on-good-health-and-well-being";
export * as MouOnGoodHealthAndWellBeing from "./mou-on-good-health-and-well-being";
export * as Sdg1NoPoverty from "./sdg-1-no-poverty";
export * as Sdg2ZeroHunger from "./sdg-2-zero-hunger";
export * as Sdg3GoodHealthAndWellBeing from "./sdg-3-good-health-and-well-being";
export * as Sdg4QualityEducation from "./sdg-4-quality-education";
export * as Sdg5GenderEquality from "./sdg-5-gender-equality";
export * as Sdg6CleanWaterAndSanitation from "./sdg-6-clean-water-and-sanitation";
export * as Sdg7AffordableAndCleanEnergy from "./sdg-7-affordable-and-clean-energy";
export * as Sdg8DecentWorkAndEconomicGrowth from "./sdg-8-decent-work-and-economic-growth";
export * as Sdg9IndustryInnovationAndInfrastructure from "./sdg-9-industry-innovation-and-infrastructure";
export * as Sdg10ReducedInequalities from "./sdg-10-reduced-inequalities";
export * as Sdg11SustainableCitiesAndCommunities from "./sdg-11-sustainable-cities-and-communities";
export * as CounsellingMentalWellbeingCentreWeDost from "./counselling-mental-wellbeing-centre-we-dost";
export * as PoliciesOnQualityEducation from "./policies-on-quality-education";
export * as PoliciesOnGenderEquality from "./policies-on-gender-equality";
export * as PolicyOnCleanWaterAndSanitation from "./policy-on-clean-water-and-sanitation";
export * as Sdg6WaterConservationInitiatives from "./sdg-6-water-conservation-initiatives";
export * as PolicyOnAffordableAndCleanEnergy from "./policy-on-affordable-and-clean-energy";
export * as MouOnAffordableAndCleanEnergy from "./mou-on-affordable-and-clean-energy";
export * as PolicyOnDecentWorkAndEconomicGrowth from "./policy-on-decent-work-and-economic-growth";
export * as PolicyOnReducedInequalities from "./policy-on-reduced-inequalities";
export * as PolicyOnSustainableCitiesAndCommunities from "./policy-on-sustainable-cities-and-communities";
