export const DEANS = [
  {
    name: "Mr. Pranav Roach",
    role: "Hughes Network Systems India Limited",
    desg: "President",
    img: "/advisory/pranav.webp",
  },
  {
    name: "Prof. Kavi Arya",
    role: "Department of Computer Science IIT Bombay",
    desg: "Professor",
    img: "/advisory/kavi-arya.webp",
  },
  {
    name: "Mr. Sunil Sethi",
    role: "Fashion Design Council of India",
    desg: "Chairman",
    img: "/advisory/sunil-sethi.webp",
  },
  {
    name: "Prof. Umesh Rai",
    role: "Vice Chancellor, Jammu University Former Director, South Campus",
    desg: "Professor, Department of Zoology, University of Delhi",
    img: "/advisory/umesh.webp",
  },
  {
    name: "Mr. Arun Kapur",
    role: "Royal Academy Bhutan Director, Vasant Valley School Vasant Kunj",
    desg: "Director",
    img: "/advisory/arun.webp",
  },
  {
    name: "Ms. Gunmeet Bindra",
    role: "Welham's Boy's School, Dehra Dun",
    desg: "Principal",
    img: "/advisory/gunmeet.webp",
  },
  {
    name: "Dr. Hemlata Reddy",
    role: "Sri Venkateswara College, University of Delhi",
    desg: "Principal",
    img: "/advisory/hemlata.webp",
  },
  {
    name: "Dr. Suman Sharma",
    role: "Lady Shriram College",
    desg: "Principal",
    img: "/advisory/suman.webp",
  },
  {
    name: "Mr. Vinod Sood",
    role: "Hughes Systique",
    desg: "CEO",
    img: "/advisory/vinod.webp",
  },
  {
    name: "Prof. Malashri Lal",
    role: "Academics,Dean of Colleges, Former HOD English",
    desg: "University of Delhi Formerly Dean",
    img: "/advisory/malashri.webp",
  },
  {
    name: "Prof. S. G. Badrinath",
    role: "IIM-Bangalore Canara Bank Chair Banking and Finance Chair Centre for Capital Markets and Risk Management",
    desg: "",
    img: "/advisory/badri.webp",
  },
  {
    name: "Mr. Pallav Sinha",
    role: "Fullerton Securities Founder Merajob.in",
    desg: "Former CEO",
    img: "/advisory/pallav.webp",
  },
  {
    name: "Mr. Vikram Atal",
    role: "U.S. Bank Holding Company Senior Advisor- Mckinsey Consulting and Goldman Sachs",
    desg: "",
    img: "/advisory/vikram.webp",
  },
  {
    name: "Prof. Jack Copeland",
    role: "Turing Centre at the Swiss Federal Institute of Technology (ETH), Zurich, Switzerland Distinguished Professor of Philosophy, University of Canterbury, New Zealand and Co-Founder and Co-Director",
    desg: "",
    img: "/advisory/jack.webp",
  },
  {
    name: "Prof. Sunita Singh Sen Gupta",
    role: "Faculty of Management Studies, University of Delhi.",
    desg: "Professor (Ph.D.)",
    img: "/advisory/sunita.webp",
  },
  {
    name: "Mr. Pawan Jaggi",
    role: "ARSD College",
    desg: "University of Delhi Chairman",
    img: "/advisory/pawan.webp",
  },
  {
    name: "Prof. Madan M. Chaturvedi",
    role: "Department of Zoology, University of Delhi",
    desg: "HOD",
    img: "/advisory/madan.webp",
  },
  {
    name: "Prof. Anita Sharma",
    role: "K.R. Mangalam University, Gurugram",
    desg: "Professor-Chinese and Ex. Pro Vice-Chancellor",
    img: "/advisory/anita.webp",
  },
  {
    name: "Dr. Pooja Sharma",
    role: "Medanta Institute of Education and Research",
    desg: "Senior Scientist",
    img: "/advisory/pooja.webp",
  },
];
