import type { Metadata } from "next";
import "./globals.css";
import NoPaperFormProvider from "@/lib/constants/NoPaperFormProvider";
import HeaderWrapper from "./components/Header/HeaderWrapper";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
  title: "KRMU",
  description: "Generated by KRMU",
  verification: {
    google: "-bhKCuhZrMwY93wMOanH66_uVGlrdB4ZMYSEik3Zl-M",
  },
};

export default function MainWebsiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div id="main-header">
        <HeaderWrapper />
      </div>
      <NoPaperFormProvider />
      <div>{children}</div>
      <div id="main-footer">
        <Footer />
      </div>
    </>
  );
}
